---

- name: "conf: Ownership and permissions"
  file:
    state: "{{ item.state }}"
    path: "{{ item.path }}"
    owner: "{{ bsd_php_conf_owner }}"
    group: "{{ bsd_php_conf_group }}"
    mode: "{{ bsd_php_conf_mode }}"
    recurse: "{{ item.recurse|default('no') }}"
  loop:
    - {state: file, path: "{{ bsd_php_conf_file }}"}
    - {state: file, path: "{{ bsd_php_conf_fpm_file }}"}
    - {state: file, path: "{{ bsd_php_conf_ini_file }}"}
#   - {state: directory, path: "{{ bsd_php_conf_path }}/php", recurse: yes}
#   - {state: directory, path: "{{ bsd_php_conf_path }}/php-fpm.d", recurse: yes}
# TODO: Apply mode to directories

# php.conf
- name: "conf: Configure {{ bsd_php_conf_file }}"
  lineinfile:
    state: "{{ item.state|default('present') }}"
    dest: "{{ bsd_php_conf_file }}"
    regexp: "^\\s*{{ item.key }}\\s*="
    line: "{{ item.key }}={{ item.val }}"
    backup: "{{ bsd_php_backup_conf }}"
  loop: "{{ bsd_php_conf }}"
  notify: reload php-fpm

- name: "conf: Set my_php_version"
  shell: "php -v | head -1 | cut -d ' ' -f 2"  # noqa 306
  register: my_php_version
  changed_when: false

- name: "conf: Configure PHP_VERSION in {{ bsd_php_conf_file }}"
  lineinfile:
    dest: "{{ bsd_php_conf_file }}"
    regexp: "^\\s*PHP_VERSION\\s*="
    line: "PHP_VERSION={{ my_php_version.stdout }}"
    backup: "{{ bsd_php_backup_conf }}"
  when: my_php_version.stdout is defined
  notify: reload php-fpm

# php-fpm.conf
- name: "conf: Configure {{ bsd_php_conf_fpm_file }}"
  lineinfile:
    state: "{{ item.state|default('present') }}"
    dest: "{{ bsd_php_conf_fpm_file }}"
    regexp: "^\\s*{{ item.key }}\\s*="
    line: "{{ item.key }} = {{ item.val }}"
    backup: "{{ bsd_php_backup_conf }}"
  loop: "{{ bsd_php_conf_fpm }}"
  notify: reload php-fpm

# php.ini
- name: "conf: Configure {{ bsd_php_conf_ini_file }}"
  lineinfile:
    state: "{{ item.state|default('present') }}"
    dest: "{{ bsd_php_conf_ini_file }}"
    regexp: "^\\s*{{ item.key }}\\s*="
    line: "{{ item.key }} = {{ item.val }}"
    backup: "{{ bsd_php_backup_conf }}"
  loop: "{{ bsd_php_conf_ini }}"
  notify: reload php-fpm

# dir php
- name: "conf: Configure {{ bsd_php_conf_path }}/php/*"
  lineinfile:
    state: "{{ item.state|default('present') }}"
    dest: "{{ bsd_php_conf_path }}/php/{{ item.0.file }}"
    regexp: "^\\s*{{ item.1.key }}\\s*="
    line: "{{ item.1.key }} = {{ item.1.val }}"
    backup: "{{ bsd_php_backup_conf }}"
  loop: "{{ bsd_php_conf_phpd|subelements('conf') }}"
  notify: reload php-fpm

# dir php-fpm.d
- name: "conf: Configure {{ bsd_php_conf_path }}/php-fpm.d/*"
  lineinfile:
    state: "{{ item.state|default('present') }}"
    dest: "{{ bsd_php_conf_path }}/php-fpm.d/{{ item.0.file }}"
    regexp: "^\\s*{{ item.1.key }}\\s*="
    line: "{{ item.1.key }} = {{ item.1.val }}"
    backup: "{{ bsd_php_backup_conf }}"
  loop: "{{ bsd_php_conf_fpmd|subelements('conf') }}"
  notify: reload php-fpm

# EOF
...
